Repository AY2425S2-CS2103T-T17-4/tp, pull requests merged in 2025-03, with the labels that each got.

#10 create jeff-photo in docs/images
  docs/images/jeff-photo.jpg
Labels: priority.Medium

#14 rename profile photo
  docs/images/jeff-photo.jpg
  docs/images/lonelyfort.png
Labels: priority.High

#26 update AboutUs.md for Jeff
  docs/AboutUs.md
Labels: type.Task, priority.Medium

#21 Update Faizal's AboutUs
  docs/AboutUs.md
Labels: priority.High

#27 update aboutus.md for jeff's name
  docs/AboutUs.md
Labels: type.Task, priority.Medium

#36 Update readme.md as part of Week 7 tp task part 2 section A
  README.md
  docs/images/Ui.png
Labels: priority.High, type.Task

#52 Add module assignment feature to Person
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ModuleRegistry.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/ModuleRegistryTest.java
Labels: priority.High

#53 Fix checkstyle problems
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.Medium, type.Enhancement

#56 Change Module display format
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/ModuleRegistry.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#63 delete address class and make sure AB3 works
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Low

#66 Branch add favourite
  src/main/java/seedu/address/logic/commands/FavCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FavCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/favourite_star.png
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/FavCommandTest.java
  src/test/java/seedu/address/logic/parser/FavCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task

#64 Cmd nav
  src/main/java/seedu/address/logic/HistoryNavigator.java
  src/main/java/seedu/address/logic/InputHistory.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/InputHistoryTest.java
Labels: priority.Medium, type.Enhancement

#80 Edit userguide to include role format
  docs/UserGuide.md
Labels: priority.High, type.Task

#83 Update user guide excluding segments from 'Features' onwards
  docs/UserGuide.md
  docs/images/BootGui.png
Labels: priority.Low

#81 Update UG command instruction table
  docs/UserGuide.md
Labels: priority.Low, type.Enhancement

#75 Separate Role from Tag
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/tag/Role.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/personlist/PersonCard.java
  src/main/resources/images/tag_ta.png
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/RoleTest.java
  src/test/java/seedu/address/model/tag/RoleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#82 Implement mass delete
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task

#78 Fix module tab not updating bug
  build.gradle
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/GuiFilterHandler.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Sidebar.java
  src/main/java/seedu/address/ui/WindowSwitchHandler.java
  src/main/java/seedu/address/ui/modulefolders/ModuleFolders.java
  src/main/resources/view/ModuleFolders.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High, type.Bug

#86 Update user guide
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/TeaMakesMePee.png
Labels: priority.Low

#92 Update user guide
  docs/UserGuide.md
  docs/images/BootGui.png
Labels: priority.Medium

#94 Add table of content and navigation links
  docs/UserGuide.md
Labels: priority.High, type.Task

#95 Update UG with cmd illustrations, Remove tag from UI msg
  docs/UserGuide.md
  docs/images/BootGuiWindows.png
  docs/images/add_after.png
  docs/images/add_before.png
  docs/images/clear_after.png
  docs/images/clear_before.png
  docs/images/delete_after.png
  docs/images/delete_before.png
  docs/images/edit_after.png
  docs/images/edit_before.png
  docs/images/exit_before.png
  docs/images/fav_after.png
  docs/images/fav_before.png
  docs/images/find_after.png
  docs/images/find_before.png
  docs/images/helpMessage.png
  docs/images/list_after.png
  docs/images/list_before.png
  src/main/java/seedu/address/logic/Messages.java
Labels: type.Task, severity.High

#97 Branch update UG
  docs/UserGuide.md
Labels: priority.High

#98 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#99 Add back to top button for all features
  docs/UserGuide.md
Labels: priority.High, type.Task

#100 Remove duplicate list instruction
  docs/UserGuide.md
Labels: priority.High, type.Task

#104 Fix UG minor bugs
  docs/UserGuide.md
Labels: priority.Low, type.Bug

#107 Add FindSequenceDiagram and DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
Labels: priority.High

#103 Update model in developer guide
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: priority.High, type.Task

#101 Fix mass delete bug
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Bug, severity.Medium
