Repository AY2425S2-CS2103T-T17-4/tp, pull requests merged in 2025-04, with the labels that each got.

#115 Fix Cmd nav bug, improve userguide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/HistoryNavigator.java
  src/main/java/seedu/address/logic/InputHistory.java
  src/main/java/seedu/address/logic/util/ArrayDequeWithRandomAccess.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/InputHistoryTest.java
  src/test/java/seedu/address/logic/util/ArrayDequeWithRandomAccessTest.java
Labels: priority.High, type.Enhancement, type.Bug

#111 Remove tag
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/modulefolders/ModuleFolders.java
  src/main/java/seedu/address/ui/personlist/PersonCard.java
  src/main/java/seedu/address/ui/personlist/PersonListPanel.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/Main.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#118 Create an empty display for modules tab and contacts tab and add favourite file
  src/main/java/seedu/address/ui/GuiFilterHandler.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Sidebar.java
  src/main/java/seedu/address/ui/modulefolders/ModuleFolders.java
  src/main/java/seedu/address/ui/personlist/PersonCard.java
  src/main/java/seedu/address/ui/personlist/PersonListPanel.java
  src/main/resources/images/empty-folder.png
  src/main/resources/images/sad-face.png
  src/main/resources/view/Main.css
  src/main/resources/view/Sidebar.css
Labels: priority.High, type.Story

#141 Update module ug
  docs/UserGuide.md
Labels: priority.High, type.Bug, alpha-bug

#120 Fix UI codebase
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/ui/GuiFunctionHandler.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Sidebar.java
  src/main/java/seedu/address/ui/WindowSwitchHandler.java
  src/main/java/seedu/address/ui/modulefolders/ModuleFolders.java
  src/main/java/seedu/address/ui/personlist/PersonListPanel.java
Labels: type.Task, priority.Medium

#139 Allow editing of telegram
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Task, priority.Medium

#148 Update UG and DG for Telegram
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, alpha-bug

#150 Find by Email
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
Labels: type.Task, priority.Medium

#151 Add acknowledgement for AB3
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low

#153 Fix name parser allowing multiple spaces between words
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, severity.High

#154 Fix add/edit message
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: severity.Low, type.Bug, alpha-bug

#155 Fix mass delete bug for duplicate indexes
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: severity.High, alpha-bug

#156 Fix capitalisation for UG example
  docs/UserGuide.md
Labels: severity.Low, type.Bug

#159 update UG known issue
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Low, type.Enhancement

#161 Fix User Guide Gui guide image bug
  docs/UserGuide.md
  docs/images/contact-list-page.png
  docs/images/module-file-page.png
Labels: alpha-bug

#162 Update UserGuide Prefix Table
  docs/UserGuide.md
Labels: severity.Medium

#163 Userguide enhancements
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#164 Change outdated screenshots in UG
  docs/images/add_before.png
  docs/images/clear_after.png
  docs/images/list_before.png
Labels: priority.Medium, type.Bug

#165 Restructure tokenizer for find command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.High, type.Enhancement, alpha-bug

#166 Fix prefix sanitation ignoring case, Response wrong case
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
Labels: type.Bug, severity.High

#244 Change DG UML, proposals, and improve UG
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/style.puml
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
Labels: type.Bug, severity.Medium

#243 update UG fixing back to top inconsistency and 3 other issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ImprovedModelClassDiagram.png
Labels: priority.Medium, type.Enhancement, type.Bug, severity.Medium

#252 Add Use cases
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Enhancement

#249 Fix multiple spaces between numbers not recognized and 2 other issues
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Telegram.java
Labels: priority.Medium, type.Bug, severity.Medium

#242 Fix delete not updating list, edit duplicate check fail
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Bug, severity.Medium

#251 Update dev guide to match AcademySource specification
  docs/DeveloperGuide.md
  docs/images/UiClassDiagram.png
Labels: priority.High

#255 Add ModuleRegistry image and edit manual testing for saving data
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModuleRegistry.puml
  docs/images/ModuleRegistry.png
Labels: priority.Medium, type.Enhancement

#258 Fix ped feature issues
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: priority.High

#263 Fix ped feature issues
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High
